name    'ploperations-gpg'
version '0.0.1'
source 'https://github.com/puppetlabs-operations/puppet-gpg'
author 'Puppet Labs Operations'
license 'Apache License, Version 2.0'
summary 'Install and manage gpg'
description 'Provides basic gpg packages and support for running agents'
project_page 'https://github.com/puppetlabs-operations/puppet-gpg'
